### PR TITLE
Feature/filter spacescoop by institutions

### PR DESCRIPTION
**Pull request by geislor**
At the request of Meghie Rodrigues, adds functionality to search by institution name in the Space scoops listing.
image

### CODE REVIEW

**Comment by zemogle** [comment]
Thanks for PR. I'm not sure this is best implemented with a search. The PR title says "filter", why not use `list_filter = ('original_news__name',)` ?

**Comment by geislor** [comment]
> Thanks for PR. I'm not sure this is best implemented with a search. The PR title says "filter", why not use `list_filter = ('original_news__name',)` ?

Helo! I agree with you, using list_filter is a much better solution. I haven't worked with Django for a long time and honestly didn't remember this option.
I will make this change and submit a new pull request.

**Comment by zemogle** [comment]
I actually have the `list_filter` code ready to go, so don't worry :-)

**Comment by geislor** [comment]
> I actually have the `list_filter` code ready to go, so don't worry :-)

Thank you very much!

**Pull request closed without merging**
